package client;

import static live.connector.vertxui.client.fluent.FluentBase.body;
import static live.connector.vertxui.client.fluent.FluentBase.console;

import com.google.gwt.core.client.EntryPoint;

import live.connector.vertxui.client.fluent.Css;
import live.connector.vertxui.client.transport.Pojofy;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Client implements EntryPoint {

	public static String url = "/ajax";

	public Client() {
		console.log("Hi there console");
		body.div(null, "Hi there body").css(Css.fontSize, "330%");
		Pojofy.ajax("GET", url, null, null, null, this::responded);
	}

	private void responded(int responseCode, String text) {
		body.div(null, "Server said: " + text);
	}

	@Override
	public void onModuleLoad() {
	}

}
